import pg from 'pg';
const { Pool } = pg;

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

async function safeQuery(sql: string, params: any[] = []): Promise<any[]> {
  try {
    const result = await pool.query(sql, params);
    return result.rows;
  } catch {
    return [];
  }
}

function escapeHtml(value: unknown): string {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
}

function htmlWrap(title: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
<style>
  @media print { body { margin: 0; } @page { margin: 1cm; } }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; max-width: 900px; margin: 0 auto; padding: 20px; }
  h1 { color: #1E3A8A; border-bottom: 3px solid #1E3A8A; padding-bottom: 8px; }
  h2 { color: #374151; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th { background: #1E3A8A; color: white; padding: 8px 10px; text-align: left; }
  td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) { background: #f9fafb; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge-green { background: #D1FAE5; color: #047857; }
  .badge-amber { background: #FEF3C7; color: #D97706; }
  .badge-red { background: #FEE2E2; color: #B91C1C; }
  .summary-box { display: inline-block; padding: 12px 20px; background: #f0f0f0; border-radius: 8px; margin: 4px; text-align: center; }
  .summary-box .value { font-size: 28px; font-weight: bold; }
  .summary-box .label { font-size: 12px; color: #666; }
  .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 11px; color: #999; text-align: center; }
  .print-btn { background: #1E3A8A; color: white; padding: 8px 16px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; }
  .print-btn:hover { background: #1e40af; }
  @media print { .no-print { display: none; } }
</style></head><body>
<div class="no-print" style="text-align:right;margin-bottom:16px;">
  <button class="print-btn" onclick="window.print()">Print / Save as PDF</button>
</div>
${body}
<div class="footer">Generated by WalaPlus QMS Platform on ${new Date().toLocaleString()} | Confidential</div>
</body></html>`;
}

function severityBadge(s: string): string {
  const safe = escapeHtml(s);
  const c = s === 'critical' || s === 'high' ? 'red' : s === 'major' || s === 'medium' ? 'amber' : 'green';
  return `<span class="badge badge-${c}">${safe}</span>`;
}

export async function generateCapaEffectivenessReport(): Promise<string> {
  const capas = await safeQuery(`
    SELECT capa_number, title, capa_type, severity, status, assigned_to,
           effectiveness_result, effectiveness_evidence, effectiveness_reviewed_by, effectiveness_reviewed_at,
           closure_approved_by, closure_approved_at, target_date, created_at
    FROM capa_records
    WHERE effectiveness_result IS NOT NULL
    ORDER BY effectiveness_reviewed_at DESC NULLS LAST
  `);

  const effective = capas.filter(c => c.effectiveness_result === 'effective').length;
  const partial = capas.filter(c => c.effectiveness_result === 'partially_effective').length;
  const notEffective = capas.filter(c => c.effectiveness_result === 'not_effective').length;

  const rows = capas.map(c => `<tr>
    <td>${escapeHtml(c.capa_number)}</td>
    <td>${escapeHtml(c.title)}</td>
    <td>${severityBadge(c.severity)}</td>
    <td><span class="badge badge-${c.effectiveness_result === 'effective' ? 'green' : c.effectiveness_result === 'not_effective' ? 'red' : 'amber'}">${escapeHtml((c.effectiveness_result || '').replace('_', ' '))}</span></td>
    <td>${escapeHtml(c.effectiveness_reviewed_by) || '-'}</td>
    <td>${c.effectiveness_reviewed_at ? new Date(c.effectiveness_reviewed_at).toLocaleDateString() : '-'}</td>
    <td>${escapeHtml(c.effectiveness_evidence) || '-'}</td>
  </tr>`).join('');

  return htmlWrap('CAPA Effectiveness Report', `
    <h1>CAPA Effectiveness Report</h1>
    <p>Summary of corrective/preventive action effectiveness reviews.</p>
    <div style="margin:16px 0;">
      <div class="summary-box"><div class="value">${capas.length}</div><div class="label">Total Reviewed</div></div>
      <div class="summary-box"><div class="value" style="color:#047857">${effective}</div><div class="label">Effective</div></div>
      <div class="summary-box"><div class="value" style="color:#D97706">${partial}</div><div class="label">Partially Effective</div></div>
      <div class="summary-box"><div class="value" style="color:#B91C1C">${notEffective}</div><div class="label">Not Effective</div></div>
    </div>
    <h2>Detail</h2>
    <table><thead><tr><th>CAPA #</th><th>Title</th><th>Severity</th><th>Result</th><th>Reviewer</th><th>Reviewed</th><th>Evidence</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="7" style="text-align:center;color:#999">No effectiveness reviews recorded</td></tr>'}</tbody></table>
  `);
}

export async function generateCompliancePostureReport(): Promise<string> {
  const obligations = await safeQuery(`
    SELECT regulation, title, status, priority, description, last_assessment_date
    FROM compliance_obligations
    ORDER BY priority DESC, status
  `);

  const compliant = obligations.filter(o => o.status === 'compliant').length;
  const partial = obligations.filter(o => o.status === 'partially_compliant').length;
  const nonCompliant = obligations.filter(o => o.status === 'non_compliant').length;
  const notAssessed = obligations.filter(o => o.status === 'not_assessed').length;
  const total = obligations.length || 1;
  const score = Math.round((compliant + partial * 0.5) / total * 100);

  const rows = obligations.map(o => `<tr>
    <td>${escapeHtml(o.regulation) || '-'}</td>
    <td>${escapeHtml(o.title)}</td>
    <td>${severityBadge(o.priority || 'low')}</td>
    <td><span class="badge badge-${o.status === 'compliant' ? 'green' : o.status === 'non_compliant' ? 'red' : 'amber'}">${escapeHtml((o.status || '').replace('_', ' '))}</span></td>
    <td>${o.last_assessment_date ? new Date(o.last_assessment_date).toLocaleDateString() : 'Not assessed'}</td>
  </tr>`).join('');

  return htmlWrap('Compliance Posture Report', `
    <h1>Compliance Posture Report</h1>
    <p>Current regulatory compliance status across all tracked obligations.</p>
    <div style="margin:16px 0;">
      <div class="summary-box"><div class="value">${score}%</div><div class="label">Overall Score</div></div>
      <div class="summary-box"><div class="value" style="color:#047857">${compliant}</div><div class="label">Compliant</div></div>
      <div class="summary-box"><div class="value" style="color:#D97706">${partial}</div><div class="label">Partial</div></div>
      <div class="summary-box"><div class="value" style="color:#B91C1C">${nonCompliant}</div><div class="label">Non-Compliant</div></div>
      <div class="summary-box"><div class="value" style="color:#6B7280">${notAssessed}</div><div class="label">Not Assessed</div></div>
    </div>
    <h2>Obligations Detail</h2>
    <table><thead><tr><th>Regulation</th><th>Obligation</th><th>Priority</th><th>Status</th><th>Last Assessed</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5" style="text-align:center;color:#999">No obligations recorded</td></tr>'}</tbody></table>
  `);
}

export async function generatePDPLInventoryReport(): Promise<string> {
  const inventory = await safeQuery(`
    SELECT name, data_category, purpose, legal_basis, retention_period, 
           cross_border, encryption_at_rest, encryption_in_transit, access_restricted
    FROM pdpl_data_inventory
    ORDER BY data_category, name
  `);

  const incidents = await safeQuery(`
    SELECT title, severity, status, reported_date, description
    FROM data_incidents
    ORDER BY reported_date DESC
    LIMIT 20
  `);

  const guardrails = await safeQuery(`
    SELECT name, guardrail_type, is_active
    FROM pdpl_ai_guardrails
    ORDER BY is_active DESC, name
  `);

  const invRows = inventory.map(i => `<tr>
    <td>${escapeHtml(i.name)}</td>
    <td>${escapeHtml(i.data_category) || '-'}</td>
    <td>${escapeHtml(i.purpose) || '-'}</td>
    <td>${escapeHtml(i.legal_basis) || '-'}</td>
    <td>${escapeHtml(i.retention_period) || '-'}</td>
    <td>${i.cross_border ? 'Yes' : 'No'}</td>
    <td>${i.encryption_at_rest ? '✓' : '✗'} / ${i.encryption_in_transit ? '✓' : '✗'}</td>
  </tr>`).join('');

  const incRows = incidents.map(i => `<tr>
    <td>${escapeHtml(i.title)}</td>
    <td>${severityBadge(i.severity || 'low')}</td>
    <td><span class="badge badge-${i.status === 'closed' || i.status === 'resolved' ? 'green' : 'amber'}">${escapeHtml(i.status)}</span></td>
    <td>${i.reported_date ? new Date(i.reported_date).toLocaleDateString() : '-'}</td>
  </tr>`).join('');

  return htmlWrap('PDPL Data Inventory Report', `
    <h1>PDPL Data Inventory Report</h1>
    <p>Personal Data Protection Law compliance inventory and incident summary.</p>
    <div style="margin:16px 0;">
      <div class="summary-box"><div class="value">${inventory.length}</div><div class="label">Data Assets</div></div>
      <div class="summary-box"><div class="value">${incidents.length}</div><div class="label">Recent Incidents</div></div>
      <div class="summary-box"><div class="value">${guardrails.filter(g => g.is_active).length}/${guardrails.length}</div><div class="label">Active Guardrails</div></div>
    </div>
    <h2>Data Inventory</h2>
    <table><thead><tr><th>Asset</th><th>Category</th><th>Purpose</th><th>Legal Basis</th><th>Retention</th><th>Cross-border</th><th>Encryption (Rest/Transit)</th></tr></thead>
    <tbody>${invRows || '<tr><td colspan="7" style="text-align:center;color:#999">No inventory records</td></tr>'}</tbody></table>
    <h2>Recent Incidents</h2>
    <table><thead><tr><th>Title</th><th>Severity</th><th>Status</th><th>Reported</th></tr></thead>
    <tbody>${incRows || '<tr><td colspan="4" style="text-align:center;color:#999">No incidents</td></tr>'}</tbody></table>
  `);
}
