import { logger } from "./logger";

export function escHtml(s: unknown): string {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

const CELL = 'style="padding:6px 10px;border-bottom:1px solid #eee;font-size:14px;color:#111;"';
const LABEL = 'style="padding:6px 10px;border-bottom:1px solid #eee;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:.03em;"';

function row(label: string, valueHtml: string): string {
  return `<tr><td ${LABEL}>${escHtml(label)}</td><td ${CELL}>${valueHtml}</td></tr>`;
}

/** PURE — renders the email HTML + subject from a BUReport-shaped object. Email
 *  clients strip <style>/classes, so inline styles are REQUIRED here (this is
 *  email content, not the CSP-bound dashboard). */
export function renderBUReportEmailHtml(report: any, dateISO: string): { subject: string; html: string } {
  const bu = report?.bu || {};
  const s = report?.sections || {};
  const nc: string[] = report?.notConfigured || [];
  const cfg = (name: string) => nc.indexOf(name) === -1;
  const NOT_CFG = '<span style="color:#999;">Not configured yet</span>';

  const sops = cfg("sops") && s.sops ? `${escHtml((s.sops.policies || []).length || s.sops.total || 0)} controlled documents` : NOT_CFG;
  const kpis = cfg("kpis") && s.kpis ? `${escHtml(s.kpis.pct ?? 0)}% (${escHtml(s.kpis.done ?? 0)}/${escHtml(s.kpis.total ?? 0)})` : NOT_CFG;

  let cleanup = NOT_CFG;
  if (cfg("cleanup") && s.cleanup) {
    const parts: string[] = [];
    if (s.cleanup.deals && s.cleanup.deals.modules) {
      const d = s.cleanup.deals.modules;
      parts.push(`Deals merged: ${escHtml(d.Deals && d.Deals.verified_merges || 0)} · Accounts: ${escHtml(d.Accounts && d.Accounts.verified_merges || 0)}`);
    }
    if (s.cleanup.leads) parts.push(`Outstanding leads: ${escHtml(s.cleanup.leads.outstanding_leads || 0)}`);
    cleanup = parts.join("<br>") || "&mdash;";
  }

  let compliance = NOT_CFG;
  if (cfg("compliance") && s.compliance) {
    const parts: string[] = [];
    if (s.compliance.cs && s.compliance.cs.summary) parts.push(`CS Lifecycle violations: ${escHtml(s.compliance.cs.summary.total_violations || 0)}`);
    if (s.compliance.stageAging && s.compliance.stageAging.summary) parts.push(`Deal stage-aging violations: ${escHtml(s.compliance.stageAging.summary.total_violations || 0)}`);
    if (s.compliance.dealCompliance) {
      const dc = s.compliance.dealCompliance;
      if (dc.checked > 0) {
        const sar = `SAR ${(Number(dc.at_risk_sar) || 0).toLocaleString()}`;
        parts.push(`Deal docs: ${escHtml(dc.compliant || 0)}/${escHtml(dc.checked)} compliant (${dc.compliant_rate == null ? "&mdash;" : escHtml(dc.compliant_rate) + "%"}) · At-risk (missing docs): ${escHtml(sar)}`);
        if (Array.isArray(dc.by_stage) && dc.by_stage.length) {
          const st = dc.by_stage.map((x: any) => `${escHtml(x.stage)}: ${escHtml(x.missing)} missing`).join(" · ");
          parts.push(`By stage — ${st}`);
        }
        if (Array.isArray(dc.top_missing_docs) && dc.top_missing_docs.length) {
          const md = dc.top_missing_docs.slice(0, 3).map((m: any) => `${escHtml(m.label)} (${escHtml(m.count)})`).join(", ");
          parts.push(`Top missing docs: ${md}`);
        }
      } else {
        parts.push(`Deal docs: no deals checked yet`);
      }
    }
    compliance = parts.join("<br>") || "&mdash;";
  }

  const actions = cfg("actions") && s.actions ? `${escHtml(s.actions.openCapas || 0)} open CAPAs` : NOT_CFG;

  const subject = `Quality Report — ${bu.bu_name || "BU"} — ${dateISO}`;
  const html =
    `<div style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:0 auto;color:#111;">` +
      `<h2 style="font-size:18px;margin:0 0 4px;">Quality Report — ${escHtml(bu.bu_name)}</h2>` +
      `<div style="font-size:12px;color:#666;margin-bottom:14px;">${escHtml(bu.channel)} · segment ${escHtml(bu.segment)} · ${escHtml(dateISO)}</div>` +
      `<table style="border-collapse:collapse;width:100%;border:1px solid #eee;">` +
        row("SOPs", sops) + row("KPIs", kpis) + row("Data cleanup", cleanup) +
        row("Compliance", compliance) + row("Open actions", actions) +
      `</table>` +
      `<div style="font-size:11px;color:#999;margin-top:14px;">Generated by ExampleOrg QMS — Quality Reports.</div>` +
    `</div>`;
  return { subject, html };
}

/** Compose the email for a BU from live data. Returns null when the BU doesn't exist. */
export async function buildBUReportEmail(
  buKey: string, dateISO: string,
): Promise<{ subject: string; html: string; headEmail: string | null; buName: string } | null> {
  const { getBUReport } = await import("./qualityReportsAggregator");
  const report = await getBUReport(buKey);
  if (!report) return null;
  const { subject, html } = renderBUReportEmailHtml(report, dateISO);
  return { subject, html, headEmail: report.bu.head_email ?? null, buName: report.bu.bu_name };
}

/** Decide the recipient for a send. `mode:'self'` ALWAYS uses the caller's
 *  session email — never a client-supplied address (no open-relay). */
export function resolveEmailRecipient(
  mode: string, headEmail: string | null, sessionEmail: string | null,
): { to: string } | { error: string; status: 400 } {
  if (mode === "self") {
    return sessionEmail ? { to: sessionEmail } : { error: "Could not resolve your email.", status: 400 };
  }
  if (mode === "head") {
    return headEmail ? { to: headEmail } : { error: "This BU has no head email mapped.", status: 400 };
  }
  return { error: "Invalid mode.", status: 400 };
}
